--COLOCANDO EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--CONSTRAINT(REGRA) CHECK
EXEC SP_HELP TB_CARGO

--CHECK PARA A COLUNA SALARIO_INIC(NÃO PODE SER NEGATIVA)
/*
SINTAXE CONSTRAINT CHECK
ALTER TABLE <NOME_TABELA>
ADD 
CONSTRAINT <NOME_INTERNO_REGRA> CHECK(NOME_COLUNA<CONDIÇÃO>)
*/
ALTER TABLE TB_CARGO
ADD
CONSTRAINT CK_CARGO_SALARIOINC CHECK(SALARIO_INC>0)

EXEC SP_HELP TB_CARGO

--CONSTRAINT UNIQUE
--COLUNA CPF NÃO PODE REPETIR
/*
SINTAXE DA CONSTRAINT UNIQUE
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> UNIQUE(NOME_COLUNA)
*/
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT UQ_EMPREGADO_CPF UNIQUE(CPF)

EXEC SP_HELP TB_EMPREGADO