--COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

EXEC SP_HELP TB_EMPREGADO

--ADICIONAR A COLUNA CPF NA COLUNA TB_EMPREGADO
ALTER TABLE TB_EMPREGADO
ADD CPF BIGINT NOT NULL

--CONSULTAR A TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO