--LISTAR OS FUNCIONARIOS QUE POSSUEM SALARIO ENTRE 600 E 4500
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO BETWEEN 600 AND 4500
ORDER BY 3
----------------------------------------------------------------
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO >= 600 AND SALARIO <= 4500
ORDER BY 3

SELECT *
FROM TB_PEDIDOS

--FAZER UMA QUERY PARA LISTAR OS PEDIDOS ENTRE 10 E 30
SELECT *
FROM TB_PEDIDOS
WHERE NUM_PEDIDO BETWEEN 10 AND 20
ORDER BY NUM_PEDIDO

--NOT BETWEEN
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO BETWEEN 600 AND 4000
ORDER BY 3

SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO NOT BETWEEN 600 AND 4000  
ORDER BY 3