--COLOCAR EM USO O BANCO SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--CLAUSULA WHERE
/*
OPERADORES RELACIONAIS
= IGUAL
<> OU != DIFERENTE
> MAIOR QUE
< MENOR QUE
>= MAIOR QUE OU IGUAL
<= MENOR QUE OU IGUAL
*/

--FAZER UMA QUERY PARA RETORNAR O COD_DEPTO, NOME, SALARIO
--COM O FILTRO DA COLUNA SALARIO IGUAL 3000
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO = 3000

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE POSSUEM SALARIO DIFERENTE DE 3000
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO != 3000
ORDER BY SALARIO
-----------------------
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO <> 3000
ORDER BY SALARIO

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE GANHAM MAIS QUE 600
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO > 600
ORDER BY SALARIO

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE GANHAM IGUAL OU MAIS QUE 600
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO >= 600
ORDER BY SALARIO

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE GANHAM MENOS QUE 700
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO < 700
ORDER BY SALARIO DESC