--COLOCAR EM USO O BANCO SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--COLUNA CALCULADA
--FAZER UMA QUERY PARA RETORNAR O NOM DO FUNCIONÁRIO E O SALARIO
--EXIBIR UMA COLUNA COM UM AUMENTO DE 10% NO SALARIO
SELECT NOME
      ,SALARIO
      ,SALARIO * 1.10 AS SALARIO_ATUAL
FROM TB_EMPREGADO

--CLAUSULA TOP
--FAZER UMA QUERY PARA LISTAR OS 05 EMPREGADOS MAIS ANTIGOS
SELECT TOP(05) NOME
      ,DATA_ADMISSAO
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO

--FAZER UMA QUERY PARA LISTAR OS 05 EMPREGADOS MAIS NOVOS
SELECT TOP(05) NOME
      ,DATA_ADMISSAO
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO DESC