--COLOCAR EM USO O BANCO SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--SINTAXE DO SELECT
/*
SELECT <NOME_COLUNA(S)>
FROM <NOME_TABELA>
WHERE <CONDIÇÃO>
GROUP BY <NOME_COLUNA(S)>
HABING <CONDIÇÃO>
ORDER BY <NOME_COLUNA(S)>
*/

--FAZER UM QUERY PARA RETORNAR TODAS AS COLUNAS DA TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO

--ESPECIFICAR O NOME DAS COLUNAS QUE QUEREMOS VIZUALIZAR NA QUERY
--FAZER UMA QUERY PARA RETORNAR O NOME E SALARIO DA TB_EMPREGADO
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO

--FAZER UMA QUERY PARA RETORNAR O NOME E SALARIO DA TB_EMPREGADO
--MAS O NOME DEVE VIR EM ORDEM CRESCENTE OU ASCENDENTE
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME ASC
--OU
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME

--FAZER UMA QUERY PARA RETORNAR O NOME E SALARIO DA TB_EMPREGADO
--MAS O NOME DEVE VIR EM ORDEM DECRESCENTE OU DESCENDENTE
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME DESC