--COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

/*
SINTAXE DO COMANDO PARA CRIAR TABELA
CREATE TABLE <NOME_TABELA>
(
DECLARAR OS CAMPOS E TIPOS DE DADOS
)
*/
--CHAR(10)
--J O N A S _ _ _ _ _
--VACHAR(10)
--J O N A S

--CRIAR A TABELA TB_DEPARTAMENTO
CREATE TABLE TB_DEPARTAMENT
(COD_DEPTO INT PRIMARY KEY
,DEPTO VARCHAR(25) NOT NULL
)

-- VERIFICAR A ESTRUTURA DA TABELA
EXEC SP_HELP TB_DEPARTAMENT

--CONSULTAR OS REGISTROS DA TABELA TB_DEPARTAMENT
--SELECT
/*	
SELECT <CAMPOS>
FROM <NOME_TABELA>
*/

SELECT *
FROM TB_DEPARTAMENT