--CRIAR O BANCO DE DADOS SISTEMA_PEDIDOS
CREATE DATABASE SISTEMA_PEDIDOS
--COLOCAR O BANCO DE DADOS SISTEMA_PEDIDOS EM USO
USE SISTEMA_PEDIDOS
--EXECUTAR A PROCEDURE DE SISTEMA SP_HELPDB
--VIZUALIZAR O TAMANHO DO BANCO SISTEMA_PEDIDOS/PASTA
EXEC SP_HELPDB SISTEMA_PEDIDOS
-- VIZUALIZAR O TAMANHO DO BANCO MODELO/PASTA
EXEC SP_HELPDB MODEL
--AO CRIAR O BANCO DE DADOS, 2 ARQUIVOS SÃO CRIADOS
--O COM EXTENSÃO MDF
--E O COM EXTENSÃO LDF