USE SISTEMA_PEDIDOS
--SINTAXE DA CHAVE ESTRANGEIRA
/*
CONSTRAINT <NOME_FK> FOREIGN KEY(CAMPO)
REFERENCES <NOME_TABELA>(CAMPO-CHAVE PRIMARIA)
*/
--COD_DEPT
--COD_CARGO
--NA TB_EMPREGADO ESTA COD_DEPTO, E NA TB_DEPARTAMENTO ESTA COD_DEPT
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT FK_CODDEPT FOREIGN KEY(COD_DEPTO)
REFERENCES TB_DEPARTAMENTO(COD_DEPT)

ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT FK_CODCARGO FOREIGN KEY(COD_CARGO)
REFERENCES TB_CARGO(COD_CARGO)

--VIZUALIZAR A ESTRUTURA DA TABELA EMPREGADO
EXEC SP_HELP TB_EMPREGADO