--COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--TABELAS EXISTENTES O BANCO EM USO
SELECT *
FROM SYS.TABLES

--CRIAR A TABELA TB_CARG
CREATE TABLE TB_CARG
(COD_CARG INT NOT NULL
,CARGO VARCHAR(30) NOT NULL
,SALARIO_INIC FLOAT NOT NULL
,CONSTRAINT PK_CODCARG PRIMARY KEY(COD_CARG)
)

--VIZUALIZAR A ESTRUTURA DA TABELA
EXEC SP_HELP TB_CARG
EXEC SP_HELP TB_DEPARTAMENT