USE SISTEMA_PEDIDOS
--CRIAR A TABELA TB_EMPREGADO
--CONSTRAINT DE CHAVE PRIMARIA PARA A COLUNA CODFUN
--CONSTRAINT DE COD_DEPTO E COD_CARGO
CREATE TABLE TB_EMPREGADO
(CODFUN INT NOT NULL
,NOME VARCHAR(35) NOT NULL
,NUM_DEPEND SMALLINT NOT NULL
,DATA_NASCIMENTO DATETIME NOT NULL
,COD_DEPTO INT NOT NULL
,COD_CARGO INT NOT NULL
,DATA_ADMISSAO DATETIME NOT NULL
,SALARIO NUMERIC(18,2) NOT NULL
,PREMIO_MENSAL NUMERIC(10,2) NOT NULL
,SINDICALIZADO CHAR(1) NOT NULL
,OBS TEXT NOT NULL
,FOTO IMAGE NOT NULL
,COD_SUPERVISOR INT NOT NULL
,CONSTRAINT PK_CODFUN PRIMARY KEY(CODFUN)
)

NUMERIC(5,2)
--_ _ _, _ _ EXPLICAÇÃO DA LINHA ACIMA: ANTES DA VIRGULA NO MAXIMO 999, DEPOIS DA VIRGULA OS VALORES DECIMAIS.