USE SISTEMA_PEDIDOS

--IDENTITY - AUTONUMERAÇÃO
--CRIAR A TABELA TB_DEPENDENTE COM A COLUNA COD_DEPENDENTE AUTONUMERAÇÃO
CREATE TABLE TB_DEPENDENTE
(COD_DEPENDENTE INT IDENTITY(1,1)
,CODFUN INT NOT NULL
,NOME CHAR(50) NOT NULL
,DATA_NASCIMENTO DATE NOT NULL
)

EXEC SP_HELP TB_DEPENDENTE

--ACRESCENTAR AS CHAVES PRIMARIA E ESTRAGEIRA
ALTER TABLE TB_DEPENDENTE
ADD CONSTRAINT PK_DEPENDENTE_CODDEP PRIMARY KEY(COD_DEPENDENTE)
,CONSTRAINT FK_DEPENDENTE_CODFUN FOREIGN KEY(CODFUN)
REFERENCES TB_EMPREGADO(CODFUN)