--POPULAR TABELA TB_CARGO
SELECT *
FROM TB_CARGO
--INSERT POSICIONAL
/*
INSERT INTO TB_CARGO
VALUES(DECLARAR AS INFOTMAÇÕES DE CADA COLUNA 
       RESPEITANDO A ORDEM DE CRIAÇÃO NA TABELA)
*/
INSERT INTO TB_CARGO
VALUES(1,'SUPERVISORA COMERCIAL',8300)

SELECT *
FROM TB_CARGO

--INSERIR MAIS DE UM REGISTRO NA TABELA
INSERT INTO TB_CARGO
VALUES(2,'QUALIDADE',2400)
     ,(3,'DIRETOR',12000)
     ,(4,'COMPRADOR',800)

SELECT *
FROM TB_CARGO