--COLOCAR EM USO O BANCO DE DADOS PEDIDOS
USE PEDIDOS
SELECT *
FROM TB_CARGO

--COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS
SELECT *
FROM TB_CARGO

--INSERIR OS REGISTROS DA TABELA TB_CARGO QUE ESTÁ NO BANCO DE DADOS PEDIDOS
INSERT INTO TB_CARGO(COD_CARGO,CARGO,SALARIO_INC)
SELECT COD_CARGO,CARGO,SALARIO_INC
FROM PEDIDOS..TB_CARGO
WHERE COD_CARGO > 6

SELECT *
FROM TB_CARGO
---------------------------------------------------------------------------------------------------
--CRIAR UMA TABELA COM O NOME TB_CLIENTE
CREATE TABLE TB_CLIENTE
(CODCLI INT PRIMARY KEY
,NOME CHAR(50)
,ESTADO CHAR(2)
)

SELECT *
FROM TB_CLIENTE

--CLAUSULA TOP	
--INSERIR 10 REGISTROS DA TABELA TB_CLIENTE DO BANCO DE DADOS PEDIDOS
--NA TABELA TB_CLIENTE DO BANCO DE DADOS SISTEMA_PEDIDOS
INSERT TOP(10) INTO TB_CLIENTE(CODCLI,NOME,ESTADO)
SELECT CODCLI,NOME,ESTADO
FROM PEDIDOS..TB_CLIENTE

SELECT *
FROM TB_CLIENTE

SELECT *
FROM PEDIDOS..TB_CLIENTE

--INSERIR OS REGISTROS DO ESTADO 'SC' NA TABELA TB_CLIENTE
INSERT INTO TB_CLIENTE(CODCLI,NOME,ESTADO)
SELECT CODCLI,NOME,ESTADO
FROM PEDIDOS..TB_CLIENTE
WHERE ESTADO = 'SC'

SELECT *
FROM TB_CLIENTE

--SINTAXE DO INSERT SELECT
/*
INSERT INTO <NOME_TABELA>(COLUNA(S))
SELECT ((COLUNA(S))
FROM <NOME_BANCO_DADOS>..<NOME_TABELA> --INDENTIFICA O NOME DO BANCO QUANDO VOU BUSCAR DADOS DE UMA TABELA QUE ESTÁ EM OUTRO BANCO SE NÃO SÓ FROM <NOME_TABELA>
WHERE <CONDIÇÃO>
/*