--FAZER UMA QUERY(CONSULTA) NA TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO
--INSERT DECLARATIVO
--TESTAMOS A REGRA FK-FOREIGN KEY DA COLUNA COD_DEPTO
INSERT INTO TB_EMPREGADO(CODFUN,NOME,NUM_DEPEND
                         ,DATA_NASCIMENTO,COD_DEPTO
                         ,COD_CARGO,DATA_ADMISSAO,SALARIO
                         ,PREMIO_MENSAL,SINDICALIZADO
                         ,OBS,FOTO,COD_SUPERVISOR,CPF)
VALUES(1,'OLAVO TRINDADE',4
      ,'1950/10/05'
      ,4 --SE COLOCAR 7 OCORRE ERRO POIS NA TABELA TB_DEPARTAMENTO QUE É A FK COMO COD_DEPTO TEM SOMENTE 5 DEPARTAMNETOS.
      ,2
      ,'1986/06/06'
      ,3000
      ,1200
      ,'S'
      ,'N/A'
      ,'N/A'
      ,1
      ,14588876544)

EXEC SP_HELP TB_EMPREGADO

SELECT *
FROM TB_DEPARTAMENTO

SELECT *
FROM TB_EMPREGADO