--LISTA: IN / NOT IN
--FAZER UMA QUERY PARA EXIBIR OS FUNCIONARIOS DOS DEPARTAMENTOS 4,5,7 OU 8
SELECT NOME
      ,COD_DEPTO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 4 
   OR COD_DEPTO = 5
   OR COD_DEPTO = 7
   OR COD_DEPTO = 8
ORDER BY 2

--USANDO IN NA QUERY ANTERIOR
SELECT NOME
      ,COD_DEPTO
FROM TB_EMPREGADO
WHERE COD_DEPTO IN(4,5,7,8)
ORDER BY 2

--EXIBIR OS CLIENTES DOS ESTADOS: AM,PR,RJ E SP
SELECT CODCLI
      ,ESTADO
FROM TB_CLIENTE
WHERE ESTADO IN('AM','PR','RJ','SP')
ORDER BY 2

--EXIBIR OS CLIENTES DE TODOS OS ESTADOS, EXCLUINDO OS ESTADOS: AM,PR,RJ E SP
SELECT CODCLI
      ,ESTADO
FROM TB_CLIENTE
WHERE ESTADO NOT IN('AM','PR','RJ','SP')
ORDER BY 2

