--OPERADORES LOGICOS
/*
OPERADOR     DESCRIÇÃO
   AND       COMBINA DUAS EXPRESSÃOES E EXIGE QUE SEJAM VERDADEIRAS PARA QUE O REGISTRO
             SEJA APRESENTADO

   OR        COMBINA DUAS EXPRESSÕES E EXIGE QUE PELO MENOS UMA SEJA VERDADEIRA PARA QUE 
             O REGISTRO SEJA RETORNADO

   NOT       INVERTE O RESULTADO LÓGICO DA EXPRESSÃO À DIREITA, OU SEJA, SE A EXPRESSÃO
             É VERDADEIRA, ELE RETORNA FALSO E VICE-VERSA
*/
--LISTAR OS FUNCIONARIOS DO DEPARTAMENTO 2 E COM SALARIO MAIOR QUE 500
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 2 AND SALARIO > 500

--LISTAR OS FUNCIONARIOS DO DEPARTAMENTO 2 E COM SALARIO MAIOR QUE 500
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 2 OR SALARIO > 500
ORDER BY 1

--LISTAR OS FUNCIONARIOS QUE PERTEMCEM AO DEPARTAMENTO AGUAL A 4
SELECT *
FROM TB_EMPREGADO
WHERE COD_DEPTO = 4