--OPERADOR LIKE
--EXIBIR NOME DE FUNCIONÁRIO INICIANDO COM JOSE OU JOÃO
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JOSE%'
OR NOME LIKE 'JOÃO%'

--EXIBIR NOME DE FUNCIONÁRIO INICIANDO COM JOSE OU JOSÉ
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JOSE%'
OR NOME LIKE 'JOSÉ%'
--FORMA SIMPLIFICADA
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JOS[EÉ]%'

--NOME DO FUNCIONÁRIO QUE CONTEM SOUSA OU SOUZA
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%SOUSA%'
OR NOME LIKE '%SOUZA%'
--FORMA SIMPLIFICADA
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%SOU[SZ]A%'

--NÃO CONHECEMOS A PRIMEIRA LETRA E A SEGUNDA LETRA CONHECEMOS: "U"
SELECT NOME 
FROM TB_EMPREGADO
WHERE NOME LIKE '_U%'

--NÃO CONHECEMOS A PRIMEIRA LETRA E A SEGUNDA LETRA CONHECEMOS: "U" OU "Ú"
SELECT NOME 
FROM TB_EMPREGADO
WHERE NOME LIKE '_[UÚ]%'

--CONHECEMOS A PRIMEIRA LETRA "L" E NÃO CONHECEMOS 4 LETRAS "_ _ _ _"
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'L____%'

--EVITE FAZER CONSULTA COM OPERADOR LIKE ENVOLVENDO NÚMEROS, PODE ATÉ RETORNAR O RESULTADO, MAS EM GRANDES BASES ELE VAI SE PERDER
--OPERADOR LIKE SEMPRE PARA TEXTO