SELECT *
FROM TB_EMPREGADO
ORDER BY NOME

--EXIBIR OS FUNCIONÁRIOS COM O NOME INICIANDO EM "C"
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'C%'

--EXIBIR OS FUNCIONÁRIOS ONDE O NOME INICIA COM "JOÃO"
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JOÃO%'

--EXIBIR NOMES DE FUNCIONÁRIOS QUE INICIAM COM "JO"
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JO%'

--EXIBIR NOMES DE FUNCIONÁRIOS QUE INICIAM COM "J", COLUNAS SALÁRIO E CPF, ORDENANDO POR SALÁRIO
SELECT NOME,SALARIO,CPF
FROM TB_EMPREGADO
WHERE NOME LIKE 'J%'
ORDER BY 2

--EXIBIR NOMES DE FUNCIONÁRIOS QUE TERMINAM COM "SILVA"
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%SILVA'

--EXIBIR NOMES DE FUNCIONÁRIOS QUE TERMINAM COM "ZA"
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%ZA'

--EXIBIR NOMES DE FUNCIONÁRIOS QUE CONTEM A PALAVRA "MARIA" NO NOME
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%MARIA%'