--COLOCAR EM USO O BANCO SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--CONSULTAR A TABELA TB_EMPREGADO RETORNANDO AS COLUNAS NOME, SALARIO
--ORDENANDO O NOME EM ORDEM ASCENDENTE
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME

--ORDERNAR POR POSIÇÃO DA COLUNA NOME
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY 1

--ORDERNAR POR POSIÇÃO DA COLUNA SALARIO
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY 2

--NA QUERY ACIMA ORDERNAR A COLUNA SALARIO EM ORDEM DECRESCENTE
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY 2 DESC
------------------------------------------------------------------
--ORDENAR POR DUAS COLUNAS OU CAMPOS
--FAZER UMA QUERY PARA RETORNAR O CODDEPTO, NOME E SALARIO
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO,NOME

--ORDENAÇÃO DA COLUNA NOME EM ORDEM DECRESCENTE
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO,NOME DESC

--ORDERNAR POR COD_DEPTO SEGUIDO DA COLUNA SALARIO DO MAIOR PARA O MENOR
SELECT COD_DEPTO
      ,NOME
      ,SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO,SALARIO DESC