--FAZER UMA QUERY NA TABELA TB_DEPENDENTE
SELECT *
FROM TB_DEPENDENTE

--VIZUALIZAR A ESTRUTURA DA TB_DEPENDENTE
EXEC SP_HELP TB_DEPENDENTE

--INSERIR UM REGISTRO NA TABELA TB_DEPENDENTE
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(1,'PEDRO','1987/01/10')

--INSERIR O SEGUNDO REGISTRO
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(2,'CARLOS','1988/10/01')

--CONSULTAR A TABELA TB_DEPENDENTE
SELECT *
FROM TB_DEPENDENTE

--INSERIR O TERCEIRO REGISTRO
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(2,'ALBERTO',NULL) --SCRIPT DEU ERRO POIS NÃO PODE TER A DATA DE NASCIMENTO COMO 'NULL'

--CORREÇÃO DO SCRIPT ANTERIOR
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(2,'ALBERTO','1990/07/20')

--TIVEMOS O ERRO COM NULL NA DATA E O DE MUDAR A ORDEM DA DATA DE '1990/20/07' PARA A DO SCRIPT, 
--LOGO A NUMERÇÃO FOI PARA '5', PERDEMOS A NUMERAÇÃO '3' E '4'