--VIZUALIZAR A ESTRUTURA DA TB_DEPARTAMENTO
EXEC SP_HELP TB_DEPARTAMENTO

SELECT *
FROM TB_DEPARTAMENTO

--INSERT DECLARATIVO
--CHAVE DUPLICADA
INSERT INTO TB_DEPARTAMENTO(COD_DEPT,DEPT)
VALUES (4,'PRODU플O')

--SCRIPT CORRETO
INSERT INTO TB_DEPARTAMENTO(COD_DEPT,DEPT)
VALUES (5,'PRODU플O')

SELECT *
FROM TB_DEPARTAMENTO

--TESTAR O COD_CARGO NA TB_CARGO
SELECT *
FROM TB_CARGO

INSERT INTO TB_CARGO(COD_CARGO,CARGO,SALARIO_INC)
VALUES (5,'VENDEDOR(A)',500)

--VIZUALIZAR A ESTRUTURA DA TABELA TB_CARGO
EXEC SP_HELP TB_CARGO

--TESTAR A CONSTRAINT DE CHECK NA COLUNA SALARIO_INC
--INSERT POSICIONAL
INSERT INTO TB_CARGO
VALUES(6,'REPRESENTANTE DA DIRE플O',-890)

--SCRIPT CORRETO
INSERT INTO TB_CARGO
VALUES(6,'REPRESENTANTE DA DIRE플O',890)

SELECT *
FROM TB_CARGO